### ISSUE TITLE
What's odd about BottleJS?

### ISSUE THREAD

**Issue by young-steveo** [CrowdHailer/IOC-example.js#1]
I'd be happy to explain or document any weirdness. :smile:

**Comment by CrowdHailer** [comment]
Amazing issue. thanks very much.

I think I was confused about the concept of middleware.
I found it while look for projects that had some similarity to the stuff talked about by Nicholas Zakas and embodied in t3, it seamed related in some ways and not others. Is there a blog explaining the why? a bit more or an example project. The docs are great but I am not sure for what purpose I employ bottle js

I will try and look at bottle a bit more and see if I can come up with a more useful question

**Comment by young-steveo** [comment]
Unfortunately, no blog post; I tried to cover as much as I could in the readme.  

Bottle is really just a fancy IoC container with a small footprint.  It has a bunch of ways you can modify a "service" object, like decorators and middleware, but usually you just use `bottle.service` and `bottle.factory` to wire up all of your objects with their dependencies.  Everything else is just sugar, or customizations to certain behaviors.

T3 breaks down a project into 1) services (singleton-like units of logic), 2) modules (page specific code tied to an element), and 3) behaviors (mix-ins for modules to share functionality).

If you were to build a project using those boundaries, bottle would allow you to easily register services using `bottle.service`, `bottle.factory` or `bottle.provider` (all of these are just fancier versions of the same thing).  You would register modules the same way, using the IoC capabilities to inject services into the modules.  Finally, you could use either `bottle.decorator` or `bottle.middleware` to achieve "behavior" functionality and dress up your modules with shared behavior.

Here's a quick and dirty example:

``` js
var bottle = new Bottle();

// example service:
bottle.service('AjaxService', function() { /* code to perform ajax requests */ });

// example module that uses the above service
bottle.factory('SidebarModule', function(container) {
    var Ajax = container.AjaxService;
    var SidebarModule = function() { /* uses Ajax */ };
    return new SidebarModule();
});

// example "behavior" that adds a function to the SidebarModule
bottle.decorator('SidebarModule', function(module) {
    module.newMethod = function(){ };
    return module;
});
```

Hope that makes sense.

**Comment by CrowdHailer** [comment]
That is very helpful.

How would the 'SideBar Module' access the sidebar element? would it have to look it up on the document itself. I like that in T3 modules get given the page element so that they have no knowledge of anything global window or body. But I also like the fact that in Bottle the service, factory et al are generic to things that need an element and things that don't

**Comment by CrowdHailer** [comment]
Am I correct in thinking that when retrieving a service the constructor/factory code is only called once but with a factory you can make multiple instances?

**Comment by young-steveo** [comment]
Regarding access to an element:  Bottle isn't a framework like T3.  Think of bottle as a single component or layer in an application; it's just an inversion of control container.  So, there's nothing in bottle that will query the DOM, or tie an HTML element to a service, or perform an AJAX request, etc.  It's just the container glue that allows you to manage dependencies between javascript services that you write yourself or bring in from another library.

It's especially useful if you want to build a framework from various small components instead of using an opinionated framework.  For example, you could use VueJS for building modules/components that have access to a DOM element, superagent.js for AJAX requests, grapnel.js for url routing, etc. etc., and then build the application using bottle to glue it all together.

**Comment by young-steveo** [comment]
Regarding the service/factory question:  you're almost correct.  The difference between `bottle.service`, `bottle.factory`, and `bottle.provider` is subtle, but they all end up creating a singleton-like object (i.e. factories don't build multiple instances).
- `bottle.service` lets you provide a constructor function that bottle will just instantiate for you when it is needed.
- `bottle.factory` lets you provide a factory function, in which you will build and return a constructed service that bottle will use when needed (still a singleton-like service, but you get control over building it)
- `bottle.provider` lets you programmatically build a factory function, in which that factory will build a service object for bottle.  So ultimately, this gives you the most control, but you have to write a lot more code.

The interesting thing to note, is that bottle services are lazily created.  So, until you access `bottle.container.Thing`, Thing is not actually instantiated until that very moment.  For example:

``` js
bottle.service('ThingA', function() { console.log('created A');  });
bottle.service('ThingB', function(ThingA) { console.log('created B');  }, 'ThingA');

// nothing in the console yet

bottle.container.ThingB;
// console.log: "created A"
// console.log: "created B"
```

That's a pretty powerful benefit of using the container.

**Comment by CrowdHailer** [comment]
Ok well that clears it up. I think that I am looking to make something that fits as a framework, hopefully without too many opinions but some none the less. I will have to see if bottle is part of that or an inspiration in setting it out.

So the service calls the function like `new Service` when instantiated but the factory does `factoryFunction()`?

Thanks for all the comments

**Comment by young-steveo** [comment]
Yeah, basically these examples are exactly the same functionality wise:

``` js
var Thing = function() { };

// as a service
bottle.service('Thing', Thing);

// or, as a factory
bottle.factory('Thing', function() {
    return new Thing();
});
```

**Comment by CrowdHailer** [comment]
Seams it could be overkill when you can so easily define a service with a factory. certainly a possibility of confusion between terms.
